# Thonia's Numpy Studies

[http://cs231n.github.io/python-numpy-tutorial/#numpy]

In [15]:
import numpy as np

In [16]:
n=np.arange(15)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
print(type(n))
print(n.reshape(3,5)) #inplace!
print(n.shape) #voltou ao que era antes! precisaria redefinir!

<class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(15,)


In [18]:
a=np.array([1,2,3])
print(a)
print(a.shape)
print(a[0],a[2])
a[0]=6 # Change an element of the array
print(a)

[1 2 3]
(3,)
1 3
[6 2 3]


In [19]:
b=np.array([[1,3,4],[99,2,1]])
print(b.shape)
print(b, b[1], b[0]) #b[1] é a segunda linha na verdade... 
print(b[1,1:]) #here's how you can slice/index
b2=np.arange(24)
b2=b2.reshape(4,6)
b2

(2, 3)
[[ 1  3  4]
 [99  2  1]] [99  2  1] [1 3 4]
[2 1]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
b2[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [21]:
a4=np.zeros((5,2))
b5= np.ones((1,7))
c6=np.full((2,5),8)
d7=np.eye(5)
e8 = np.random.random((2,2))  # Create an array filled with random values
print(a4)
print(b5)
print(c6)
print(d7)
print(e8)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.80614983 0.18507925]
 [0.00689301 0.73320506]]


## Deveria ser a mesma coisa embaixo, mas não é!
## Mixing integer indexing with slices yields an array of lower rank,  while using only slices yields an array of the same rank as the original array:
## Melhor não misturar integer indexing with slices!!!  A saída eu achei mais elegante e coerente.

In [22]:
d7_1=d7[1,:] #a linha toda
d7_1.shape
d7_2=d7[1:2, :] #a linha toda tb
d7_2.shape
print(d7_1,d7_1.shape)
print(d7_2,d7_2.shape)
d7_c=d7[:,2]
print(d7_c,d7_c.shape)
d7_c2=d7[:, 2:3]
print(d7_c2,d7_c2.shape)

[0. 1. 0. 0. 0.] (5,)
[[0. 1. 0. 0. 0.]] (1, 5)
[0. 0. 1. 0. 0.] (5,)
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]] (5, 1)


In [23]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


### Fazer isso que acabei de fazer acima equivale a fazer:
```python
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
```
### Veja que legal isso:

In [24]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]
[2 2]


In [25]:
#pay attention to this:
arr1=[3,4,5,6,7]
print(type(arr1))

<class 'list'>


In [26]:
#now things change...
narr1=np.array(arr1)
print(type(narr1)) #repare que é narr1 e não arr1
#becomes a np.ndarray object, que vamos trabalhar aqui em ver as diferentes funções que podemos implementar nesse objeto
#isso inclui desde operacoes aritmeticas basicas até sistemas de equacoes lineares e estatistica bascia

<class 'numpy.ndarray'>


Numpy is an n dim array object or ndarray  
provides a fast and efficient way of storing homogeneous data  
we can have nd array w/ 1 dimension or 1 row and these are rank 1 arrays  
or we can have multidimensional arrays with more than one row [[row1, row2],[row3,row4]]

In [27]:
# multidimensional array

arr2=[[1,2,3,4],[3,4,5,6]]
print(type(arr2))
print(arr2)

<class 'list'>
[[1, 2, 3, 4], [3, 4, 5, 6]]


In [28]:
narr2=np.array(arr2)
print(type(narr2))
print(narr2)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [3 4 5 6]]


In [29]:
arr3=[[1,2,3,4],[3,4,5,6],[7,8,9,6]]
narr3=np.array(arr3)
print(narr3)
#multidimensional arrays w/ 3 rows and full cols

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 6]]


In [30]:
print(narr3.shape)

(3, 4)


In [31]:
#2*2 constant arrays

full=np.full((2,2),5)

print(full)

[[5 5]
 [5 5]]


a[start:end] vai do item 0 até o item (end-1)  
a[start:] vai do item 0 até o último item  
a[:end] vai do item 0 até o item (end-1)  
a[:] é uma cópia do array inteiro  

In [32]:
#concatenate two numpy arrays

x=np.array([2,6,8,4])

y=np.array([11,8,2])

z=np.concatenate([y,x])

print(z)

[11  8  2  2  6  8  4]


In [33]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
a[np.arange(4),b]
#equivale a: a[[0,1,2,3],[0,2,0,1]]- pares x,y

array([ 1,  6,  7, 11])

In [35]:
#reverse the order
k=np.array(a[::-1])
print(k)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [36]:
##Multi-dimensional array operations
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]

narr=np.array(arr) #convert array into numpy array

print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]


In [37]:
print(narr[0]) #print first row at row index 0


[1 2 3 4]


In [38]:
print(narr[3])

[12  7 10  9]


In [39]:
print(narr[2,3]) #print contents of row with index 2 and column with index 3 [row,columm]
print(narr[3,2])

6
10


In [40]:
narr[3,2]=0 #replace value at a location
print (narr)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7  0  9]
 [ 2 11  8 10]]


In [41]:
#get the last row
print(narr[-1])

[ 2 11  8 10]


In [42]:
#get the last row
print(type(narr[-1]))

<class 'numpy.ndarray'>


In [43]:
#get the 2nd last
print(narr[-2])
# print rows and columns

print(narr[1:4,2:5]) #rows: 1 to 4-1 and columns 2 to 5-1

[12  7  0  9]
[[5 6]
 [9 6]
 [0 9]]


## Repare que se a gente extrapolar os índices, ele não reclama!

In [44]:
# print rows and columns

print(narr[1:9,2:8]) #rows: 1 to 4-1 and columns 2 to 5-1
#it doesn't complain if we extrapolate indexes!!!!!!!!

[[ 5  6]
 [ 9  6]
 [ 0  9]
 [ 8 10]]


In [45]:
###concatenation row and column wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

#concatenate row wise 

c=np.concatenate((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]]


## Indexação Booleana 
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [46]:
a = np.array([[1,2,0.1,80.1], [60, 3, 4,50.1], [2,85,5, 6],[39,39.9,40.1,45]])

In [47]:
bool_idx = (a <3 or a>40) 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
sel=[lambda x: x>3 for x in list(a.shape)]
a[sel]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [50]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[a==2])

[2. 2.]


In [51]:
print(a==2)

[[False  True False False]
 [False False False False]
 [ True False False False]
 [False False False False]]


In [52]:
print(a<3 or a>40)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [53]:
print(a<3)

[[ True  True  True False]
 [False False False False]
 [ True False False False]
 [False False False False]]


In [54]:
#com list comprehension:
a_bool1=[x for x in a.flat if x<3 or x>40]
a_bool=[lambda i: (i> 40 or i<3) for i in a.flat]
print(type(a_bool),type(a_bool1))

<class 'list'> <class 'list'>


In [100]:
print(a_bool)
print(a_bool1)
print(type(a_bool1))

[<function <listcomp>.<lambda> at 0x000001290A71CBF8>, <function <listcomp>.<lambda> at 0x000001290A71CC80>, <function <listcomp>.<lambda> at 0x000001290A71C7B8>, <function <listcomp>.<lambda> at 0x000001290A71CF28>, <function <listcomp>.<lambda> at 0x000001290A71CEA0>, <function <listcomp>.<lambda> at 0x000001290A71C048>, <function <listcomp>.<lambda> at 0x000001290A71CD90>, <function <listcomp>.<lambda> at 0x000001290A71CD08>, <function <listcomp>.<lambda> at 0x000001290A71C730>, <function <listcomp>.<lambda> at 0x000001290A71C950>, <function <listcomp>.<lambda> at 0x000001290A71C9D8>, <function <listcomp>.<lambda> at 0x00000129095A2D90>, <function <listcomp>.<lambda> at 0x00000129091AE510>, <function <listcomp>.<lambda> at 0x000001290A72E840>, <function <listcomp>.<lambda> at 0x000001290A72E488>, <function <listcomp>.<lambda> at 0x000001290A72ED90>]
[1.0, 2.0, 0.1, 80.1, 60.0, 50.1, 2.0, 85.0, 40.1, 45.0]
<class 'list'>


In [56]:
selection = (a > 40) | (a < 3)

In [57]:
a[selection]

array([ 1. ,  2. ,  0.1, 80.1, 60. , 50.1,  2. , 85. , 40.1, 45. ])

##  Erros do tipo:
#### ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
#### Quando quero colocar mais de uma condição:
- Posso selecionar elementos menores que 3 OU maiores que 40?

In [58]:
print(a)
print(a<3) #imprime toda a matriz booleana
print(a[a<3]) #só imprime os elementos onde isso for verdade)
print(a>40)

[[ 1.   2.   0.1 80.1]
 [60.   3.   4.  50.1]
 [ 2.  85.   5.   6. ]
 [39.  39.9 40.1 45. ]]
[[ True  True  True False]
 [False False False False]
 [ True False False False]
 [False False False False]]
[1.  2.  0.1 2. ]
[[False False False  True]
 [ True False False  True]
 [False  True False False]
 [False False  True  True]]


### Quando queremos fazer um OR statement, nos deparamos com o seguinte:

In [59]:
a[(a<3 or a>40)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Solução: a[(np.logical_or a<3,a>40)]

In [60]:
 a[np.logical_or (a<3,a>40)]

array([ 1. ,  2. ,  0.1, 80.1, 60. , 50.1,  2. , 85. , 40.1, 45. ])

In [61]:
np.logical_or (a<3,a>40)

array([[ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True,  True]])

### Outras seleções, no entanto, são possíveis:

In [62]:
selection = (a > 40) | (a < 3)

In [63]:
print(selection)
print(a[selection])

[[ True  True  True  True]
 [ True False False  True]
 [ True  True False False]
 [False False  True  True]]
[ 1.   2.   0.1 80.1 60.  50.1  2.  85.  40.1 45. ]


In [64]:
selec2= (a%3==0) & (a%5==0)
print(selec2)

[[False False False False]
 [ True False False False]
 [False False False False]
 [False False False  True]]


In [65]:
a[selec2]

array([60., 45.])

In [66]:
selec2= (a%3==0) | (a%5==0)
print(a[selec2])

[60.  3. 85.  5.  6. 39. 45.]


In [67]:
print("Elements of a, which are not divisible by 3:")
bool3=(a%3==0) 
print(bool3)
print(a[bool3])

Elements of a, which are not divisible by 3:
[[False False False False]
 [ True  True False False]
 [False False False  True]
 [ True False False  True]]
[60.  3.  6. 39. 45.]


In [68]:
print("Elements of a, which are not divisible by 3:")
print(a%3!=0) 
a[a%3!=0]

Elements of a, which are not divisible by 3:
[[ True  True  True  True]
 [False False  True  True]
 [ True  True  True False]
 [False  True  True False]]


array([ 1. ,  2. ,  0.1, 80.1,  4. , 50.1,  2. , 85. ,  5. , 39.9, 40.1])

### No entanto, podemos fazer tudo isso em uma linha só:

In [69]:
print(a[a>2])

[80.1 60.   3.   4.  50.1 85.   5.   6.  39.  39.9 40.1 45. ]


## Array Math:
#### available both as operator overloads and as functions in the numpy module:

In [70]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [71]:
a3=np.hstack((a,a,a)) #coloca 3 matrizes uma do lado da outra
a3

array([[ 1. ,  2. ,  0.1, 80.1,  1. ,  2. ,  0.1, 80.1,  1. ,  2. ,  0.1,
        80.1],
       [60. ,  3. ,  4. , 50.1, 60. ,  3. ,  4. , 50.1, 60. ,  3. ,  4. ,
        50.1],
       [ 2. , 85. ,  5. ,  6. ,  2. , 85. ,  5. ,  6. ,  2. , 85. ,  5. ,
         6. ],
       [39. , 39.9, 40.1, 45. , 39. , 39.9, 40.1, 45. , 39. , 39.9, 40.1,
        45. ]])

In [72]:
a4=np.vstack((a,a,a))
a4

array([[ 1. ,  2. ,  0.1, 80.1],
       [60. ,  3. ,  4. , 50.1],
       [ 2. , 85. ,  5. ,  6. ],
       [39. , 39.9, 40.1, 45. ],
       [ 1. ,  2. ,  0.1, 80.1],
       [60. ,  3. ,  4. , 50.1],
       [ 2. , 85. ,  5. ,  6. ],
       [39. , 39.9, 40.1, 45. ],
       [ 1. ,  2. ,  0.1, 80.1],
       [60. ,  3. ,  4. , 50.1],
       [ 2. , 85. ,  5. ,  6. ],
       [39. , 39.9, 40.1, 45. ]])

## Broadcasting
- Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 
- Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
- For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [73]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Isso até funciona, isso é o que a gente faz no MATLAB. Mas quando a matriz é mt grande, computar um loop explícito pode ser lento. 
- Somar um vetor v para cada linha da matriz x é equivalente a formar uma matriz vv que empilha múltiplas cópias de v e depois somar x e vv.
### Como posso implementar esse approach?

In [74]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))
print(vv) 
y=x+vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Vejam a mágica! 
### Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [75]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=x+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

## Regras do broadcasting:

- Funções que suportam broadcasting são chamadas funções universais.
- If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible in all dimensions.  
- After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [76]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


### Olha só que legal!

In [77]:
x = np.array([[1,2,3], [4,5,6]])
print(x)
print(v.shape, x.shape)
print(x+v)

[[1 2 3]
 [4 5 6]]
(3,) (2, 3)
[[2 4 6]
 [5 7 9]]


In [78]:
x.T+w

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

In [79]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [80]:
x*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## Datatypes:
#### Every numpy array is a grid of elements of the same type. 
#### Numpy provides a large set of numeric datatypes that you can use to construct arrays. 
#### Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [81]:
x1 = np.array([1, 2])   # Let numpy choose the datatype
print(x1.dtype) #imprime o tipo dos elementos de x1
print(type(x1)) #imprime o tipo do x1

int32
<class 'numpy.ndarray'>


In [82]:
x2 = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x2.dtype)  

float64


# Aqui estou 'forçando a barra' pras entradas da matriz serem inteiras

In [83]:
x3 = np.array([1.2, 2], dtype=np.int64)   # Force a particular datatype
print(x3.dtype)                         # Prints "int64"

int64


In [84]:
print(x3[0],x3[1])

1 2


# Some basic stats with numpy

In [85]:
arr=[[1,2,3,4],[3,4,5,6],[7,8,9,6],[12,7,10,9],[2,11,8,10]]
narr=np.array(arr) #convert array into numpy array
print (narr)

print('soma total =',narr.sum()) #sum all values of the array
print('soma por coluna =',narr.sum(axis=0)) #column wise sum
print('soma por linha =',narr.sum(axis=1)) #row wise sum


[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 7  8  9  6]
 [12  7 10  9]
 [ 2 11  8 10]]
soma total = 127
soma por coluna = [25 32 35 35]
soma por linha = [10 18 30 38 31]


In [86]:
#mean and medians are measures of centre tendency

narr.mean(axis=0) #column means

array([5. , 6.4, 7. , 7. ])

In [87]:
np.median(narr,axis=1) #row median

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [88]:
#variance in the data

np.std(narr) #standard dev

3.182373328193912

In [89]:
#percentile- value below which a given percentage of observations

np.percentile(narr,50,axis=1) #50th percentile

array([2.5, 4.5, 7.5, 9.5, 9. ])

In [90]:
import numpy as np
print("\nShowing some basic math on arrays:")
b=np.array([0,1,4,3,2])
print("max: {}".format(np.max(b)))
print("max: {}".format(np.average(b)))
print("max: {}".format(np.argmax(b)))
print("Shape of b: {}".format(b.shape))


Showing some basic math on arrays:
max: 4
max: 2.0
max: 2
Shape of b: (5,)


In [91]:
import numpy as np
#understand argmax
arr3=[[1,2,3,4],[3,4,5,6],[7,8,9,6]]

a=np.array(arr3)

j=np.argmax(a,axis=0) #vai buscar por coluna a posicao do primeiro elemento que for o maior de todos
k=np.argmax(a,axis=1) #vai buscar por linha a posicao do primeiro elemento que for o maior de todos
print(j)
print(k)

[2 2 2 1]
[3 3 2]


In [92]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0]))) #string.format(valores)


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


In [93]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.82296193 0.19222669 0.57636306]
 [0.12279445 0.28427326 0.05498262]
 [0.75429158 0.47869862 0.01250949]]


In [94]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3, 4)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


In [95]:
print(b)
print(type(b))

[0 1 4 3 2]
<class 'numpy.ndarray'>


In [96]:
print(a)
print(type(a))

[[1 2 3 4]
 [3 4 5 6]
 [7 8 9 6]]
<class 'numpy.ndarray'>


In [97]:
print(c)
print(type(c))

[[0.82296193 0.19222669 0.57636306]
 [0.12279445 0.28427326 0.05498262]
 [0.75429158 0.47869862 0.01250949]]
<class 'numpy.ndarray'>
